project_id = "calculadora"

[api]
enabled = true
port = 54371
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54372
shadow_port = 54370
major_version = 17

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://127.0.0.1:3000"]
jwt_expiry = 43200
enable_signup = false
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
secure_password_change = false

[auth.email.notification.password_changed]
enabled = false

[studio]
enabled = true
port = 54373

[local_smtp]
enabled = false

[storage]
enabled = false

[analytics]
enabled = true
port = 54377
backend = "postgres"
