-- Keep financial and audit writes behind the application server while retaining
-- the authenticated user's identity for ownership checks and audit records.

alter table public.transactions
  add column ledger_sequence bigint generated by default as identity;
create unique index transactions_ledger_sequence_key
  on public.transactions (ledger_sequence);

create or replace function private.assume_server_actor(actor_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if actor_id is null or not exists (select 1 from public.profiles where id = actor_id) then
    raise exception using errcode = '42501', message = 'valid_actor_required';
  end if;
  perform pg_catalog.set_config('request.jwt.claim.sub', actor_id::text, true);
  perform pg_catalog.set_config('request.jwt.claim.role', 'authenticated', true);
end;
$$;

create or replace function public.server_post_loan(actor_id uuid, command jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
begin
  perform private.assume_server_actor(actor_id);
  return public.post_loan(command);
end;
$$;

create or replace function public.server_post_capital_payment(actor_id uuid, command jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
begin
  perform private.assume_server_actor(actor_id);
  return public.post_capital_payment(command);
end;
$$;

create or replace function public.server_post_payment_adjustment(actor_id uuid, command jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
begin
  perform private.assume_server_actor(actor_id);
  return public.post_payment_adjustment(command);
end;
$$;

create or replace function public.server_edit_transaction(actor_id uuid, command jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare target public.transactions%rowtype;
begin
  perform private.assume_server_actor(actor_id);
  select * into target from public.transactions where id = (command->>'transactionId')::uuid;
  if not found then raise exception using errcode = 'P0001', message = 'transaction_not_found'; end if;
  if exists (
    select 1 from public.transactions later
    where later.loan_id = target.loan_id
      and later.status = 'posted'
      and later.ledger_sequence > target.ledger_sequence
  ) then
    raise exception using errcode = 'P0001', message = 'dependent_transactions_must_be_voided_first';
  end if;
  return public.edit_transaction(command);
end;
$$;

create or replace function public.server_void_transaction(actor_id uuid, target_transaction_id uuid, reason text)
returns jsonb language plpgsql security definer set search_path = '' as $$
begin
  perform private.assume_server_actor(actor_id);
  return public.void_transaction(target_transaction_id, reason);
end;
$$;

create or replace function public.server_record_audit_event(
  actor_id uuid,
  target_organization_id uuid,
  target_action text,
  target_entity_type text,
  target_entity_id text,
  target_details jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not private.is_active_member(target_organization_id, actor_id) then
    raise exception using errcode = '42501', message = 'active_membership_required';
  end if;
  if pg_catalog.char_length(target_action) not between 1 and 80
     or pg_catalog.char_length(target_entity_type) not between 1 and 80
     or pg_catalog.char_length(target_entity_id) not between 1 and 120
     or pg_catalog.jsonb_typeof(coalesce(target_details, '{}'::jsonb)) <> 'object' then
    raise exception using errcode = '22023', message = 'invalid_audit_event';
  end if;
  perform pg_catalog.set_config('app.business_write', 'on', true);
  insert into public.audit_events (organization_id, actor_id, action, entity_type, entity_id, details)
  values (target_organization_id, actor_id, target_action, target_entity_type, target_entity_id, coalesce(target_details, '{}'::jsonb));
end;
$$;

create or replace function public.server_create_customer(
  actor_id uuid,
  target_organization_id uuid,
  target_name text,
  target_phone text,
  target_email text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  customer_id_value uuid;
begin
  if not private.is_active_member(target_organization_id, actor_id) then
    raise exception using errcode = '42501', message = 'active_membership_required';
  end if;
  perform pg_catalog.set_config('app.business_write', 'on', true);
  insert into public.customers (organization_id, created_by, name, phone, email)
  values (target_organization_id, actor_id, pg_catalog.btrim(target_name), pg_catalog.btrim(target_phone), pg_catalog.btrim(target_email))
  returning id into customer_id_value;
  insert into public.audit_events (organization_id, actor_id, action, entity_type, entity_id, details)
  values (target_organization_id, actor_id, 'customer.created', 'customer', customer_id_value::text,
    pg_catalog.jsonb_build_object('name', pg_catalog.btrim(target_name)));
  return pg_catalog.jsonb_build_object('id', customer_id_value);
end;
$$;

create or replace function public.server_update_customer(
  actor_id uuid,
  target_organization_id uuid,
  target_customer_id uuid,
  target_archive boolean,
  target_name text default null,
  target_phone text default null,
  target_email text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  customer public.customers%rowtype;
  before_state jsonb;
begin
  if not private.is_active_member(target_organization_id, actor_id) then
    raise exception using errcode = '42501', message = 'active_membership_required';
  end if;
  select * into customer from public.customers
  where id = target_customer_id and organization_id = target_organization_id
  for update;
  if not found then
    raise exception using errcode = 'P0001', message = 'customer_not_found';
  end if;
  before_state := pg_catalog.jsonb_build_object('name', customer.name, 'phone', customer.phone,
    'email', customer.email, 'archivedAt', customer.archived_at);
  if target_archive and exists (
    select 1 from public.loans where customer_id = target_customer_id and status = 'active'
  ) then
    raise exception using errcode = 'P0001', message = 'active_loans_prevent_customer_archive';
  end if;
  perform pg_catalog.set_config('app.business_write', 'on', true);
  if target_archive then
    update public.customers set archived_at = pg_catalog.now(), updated_at = pg_catalog.now()
    where id = target_customer_id;
  else
    update public.customers set name = pg_catalog.btrim(target_name), phone = pg_catalog.btrim(target_phone),
      email = pg_catalog.btrim(target_email), updated_at = pg_catalog.now()
    where id = target_customer_id;
  end if;
  insert into public.audit_events (organization_id, actor_id, action, entity_type, entity_id, details)
  values (target_organization_id, actor_id,
    case when target_archive then 'customer.archived' else 'customer.updated' end,
    'customer', target_customer_id::text,
    pg_catalog.jsonb_build_object('before', before_state, 'after',
      case when target_archive then pg_catalog.jsonb_build_object('archivedAt', pg_catalog.now())
      else pg_catalog.jsonb_build_object('name', pg_catalog.btrim(target_name), 'phone', pg_catalog.btrim(target_phone), 'email', pg_catalog.btrim(target_email)) end));
  return pg_catalog.jsonb_build_object('id', target_customer_id, 'archived', target_archive);
end;
$$;

create or replace function public.server_update_organization_settings(
  actor_id uuid,
  target_organization_id uuid,
  target_name text,
  target_default_recipient text,
  target_prefixes jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  financing_prefix text := target_prefixes->>'financing';
  receipt_prefix text := target_prefixes->>'receipt';
  adjustment_prefix text := target_prefixes->>'adjustment';
  unique_prefix_count integer;
  before_state jsonb;
begin
  if not private.is_owner(target_organization_id, actor_id) then
    raise exception using errcode = '42501', message = 'owner_required';
  end if;
  select count(distinct value) into unique_prefix_count
  from pg_catalog.jsonb_each_text(target_prefixes) prefixes(key, value)
  where key in ('financing', 'receipt', 'adjustment');
  if pg_catalog.char_length(pg_catalog.btrim(target_name)) not between 1 and 100
     or pg_catalog.char_length(pg_catalog.btrim(target_default_recipient)) > 80
     or financing_prefix !~ '^[A-Z0-9]{1,12}$'
     or receipt_prefix !~ '^[A-Z0-9]{1,12}$'
     or adjustment_prefix !~ '^[A-Z0-9]{1,12}$'
     or unique_prefix_count <> 3 then
    raise exception using errcode = '22023', message = 'invalid_organization_settings';
  end if;
  select pg_catalog.jsonb_build_object(
    'name', organization.name,
    'defaultRecipient', organization.default_recipient,
    'prefixes', (select pg_catalog.jsonb_object_agg(kind, prefix) from public.document_counters where organization_id = target_organization_id)
  ) into before_state from public.organizations organization where id = target_organization_id for update;
  if before_state is null then
    raise exception using errcode = 'P0001', message = 'organization_not_found';
  end if;
  update public.organizations set name = pg_catalog.btrim(target_name),
    default_recipient = pg_catalog.btrim(target_default_recipient), updated_at = pg_catalog.now()
  where id = target_organization_id;
  update public.document_counters
  set prefix = case kind when 'financing' then financing_prefix when 'receipt' then receipt_prefix else adjustment_prefix end,
      updated_at = pg_catalog.now()
  where organization_id = target_organization_id;
  perform pg_catalog.set_config('app.business_write', 'on', true);
  insert into public.audit_events (organization_id, actor_id, action, entity_type, entity_id, details)
  values (target_organization_id, actor_id, 'settings.updated', 'organization', target_organization_id::text,
    pg_catalog.jsonb_build_object('before', before_state, 'after', pg_catalog.jsonb_build_object(
      'name', pg_catalog.btrim(target_name), 'defaultRecipient', pg_catalog.btrim(target_default_recipient), 'prefixes', target_prefixes)));
  return pg_catalog.jsonb_build_object('updated', true);
end;
$$;

-- Reject attempts to archive a customer while the customer still has a live loan.
create or replace function private.prevent_active_customer_archive()
returns trigger language plpgsql set search_path = '' as $$
begin
  if old.archived_at is null and new.archived_at is not null and exists (
    select 1 from public.loans where customer_id = old.id and status = 'active'
  ) then
    raise exception using errcode = 'P0001', message = 'active_loans_prevent_customer_archive';
  end if;
  return new;
end;
$$;

create trigger prevent_active_customer_archive
before update of archived_at on public.customers
for each row execute function private.prevent_active_customer_archive();

-- An edit is safe only while the target is the latest posted operation.
create or replace function private.prevent_historical_transaction_edit()
returns trigger language plpgsql set search_path = '' as $$
begin
  if coalesce(pg_catalog.current_setting('app.editing', true), '') = 'on'
     and exists (
       select 1 from public.transactions later
       where later.loan_id = old.loan_id
         and later.status = 'posted'
         and later.ledger_sequence > old.ledger_sequence
     ) then
    raise exception using errcode = 'P0001', message = 'dependent_transactions_must_be_voided_first';
  end if;
  return new;
end;
$$;

create trigger prevent_historical_transaction_edit
before update on public.transactions
for each row execute function private.prevent_historical_transaction_edit();

-- Enforce chronology and prevent two live credits against the same installment.
create or replace function private.validate_capital_payment_dates()
returns trigger language plpgsql set search_path = '' as $$
declare transaction_date_value date;
begin
  select effective_date into transaction_date_value from public.transactions where id = new.transaction_id;
  if new.next_payment_date <= transaction_date_value
     or (new.last_payment_date is not null and new.last_payment_date > transaction_date_value) then
    raise exception using errcode = '23514', message = 'invalid_capital_payment_dates';
  end if;
  return new;
end;
$$;

create trigger validate_capital_payment_dates
before insert or update on public.capital_payment_details
for each row execute function private.validate_capital_payment_dates();

create or replace function private.validate_payment_adjustment()
returns trigger language plpgsql set search_path = '' as $$
declare dependency_id uuid;
begin
  if new.next_payment_date <= new.payment_date then
    raise exception using errcode = '23514', message = 'invalid_adjustment_dates';
  end if;
  select depends_on_transaction_id into dependency_id from public.transactions where id = new.transaction_id;
  if exists (
    select 1
    from public.payment_adjustment_details details
    join public.transactions transaction on transaction.id = details.transaction_id
    where details.transaction_id <> new.transaction_id
      and transaction.status = 'posted'
      and transaction.depends_on_transaction_id = dependency_id
      and details.payment_number = new.payment_number
  ) then
    raise exception using errcode = '23505', message = 'duplicate_adjustment_for_installment';
  end if;
  return new;
end;
$$;

create trigger validate_payment_adjustment
before insert or update on public.payment_adjustment_details
for each row execute function private.validate_payment_adjustment();

-- Keep profile updates available without granting clients direct table or audit writes.
create or replace function public.update_my_profile(
  target_display_name text,
  target_organization_name text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_user_id uuid := auth.uid();
  current_membership public.organization_members%rowtype;
  clean_display_name text := pg_catalog.btrim(target_display_name);
  clean_organization_name text;
  organization_changed boolean := false;
begin
  if current_user_id is null then raise exception using errcode = '42501', message = 'authentication_required'; end if;
  if clean_display_name is null or pg_catalog.char_length(clean_display_name) not between 1 and 80 then
    raise exception using errcode = '22023', message = 'invalid_display_name';
  end if;
  select membership.* into current_membership from public.organization_members membership
  where membership.user_id = current_user_id and membership.active limit 1;
  if current_membership.user_id is null then raise exception using errcode = '42501', message = 'active_membership_required'; end if;
  perform pg_catalog.set_config('app.business_write', 'on', true);
  update public.profiles set display_name = clean_display_name, updated_at = pg_catalog.now() where id = current_user_id;
  insert into public.audit_events (organization_id, actor_id, action, entity_type, entity_id, details)
  values (current_membership.organization_id, current_user_id, 'profile.updated', 'profile', current_user_id::text, '{}'::jsonb);
  if target_organization_name is not null then
    if current_membership.role <> 'owner' then raise exception using errcode = '42501', message = 'owner_required'; end if;
    clean_organization_name := pg_catalog.btrim(target_organization_name);
    if pg_catalog.char_length(clean_organization_name) not between 1 and 100 then
      raise exception using errcode = '22023', message = 'invalid_organization_name';
    end if;
    update public.organizations set name = clean_organization_name, updated_at = pg_catalog.now()
    where id = current_membership.organization_id and name is distinct from clean_organization_name;
    organization_changed := found;
    if organization_changed then
      insert into public.audit_events (organization_id, actor_id, action, entity_type, entity_id, details)
      values (current_membership.organization_id, current_user_id, 'settings.updated', 'organization',
        current_membership.organization_id::text, '{"field":"name"}'::jsonb);
    end if;
  else
    select name into clean_organization_name from public.organizations where id = current_membership.organization_id;
  end if;
  return pg_catalog.jsonb_build_object('displayName', clean_display_name, 'organizationName', clean_organization_name,
    'organizationChanged', organization_changed);
end;
$$;

-- Authenticated clients retain read access and the narrowly scoped profile RPC.
revoke insert, update on public.customers from authenticated;
revoke update on public.organizations, public.document_counters, public.profiles from authenticated;
revoke insert, update on public.loans from authenticated;
revoke insert on public.transactions, public.schedule_versions, public.installments,
  public.capital_payment_details, public.payment_adjustment_details, public.documents,
  public.audit_events from authenticated;
revoke execute on function public.post_loan(jsonb), public.post_capital_payment(jsonb),
  public.post_payment_adjustment(jsonb), public.edit_transaction(jsonb),
  public.void_transaction(uuid, text), public.record_audit_event(uuid, text, text, text, jsonb)
  from authenticated;
revoke execute on function private.next_document_number(uuid, text), private.assert_schedule_reconciles(uuid)
  from authenticated;

revoke all on function public.server_post_loan(uuid, jsonb),
  public.server_post_capital_payment(uuid, jsonb), public.server_post_payment_adjustment(uuid, jsonb),
  public.server_edit_transaction(uuid, jsonb), public.server_void_transaction(uuid, uuid, text),
  public.server_record_audit_event(uuid, uuid, text, text, text, jsonb),
  public.server_create_customer(uuid, uuid, text, text, text),
  public.server_update_customer(uuid, uuid, uuid, boolean, text, text, text),
  public.server_update_organization_settings(uuid, uuid, text, text, jsonb)
  from public, anon, authenticated;
grant execute on function public.server_post_loan(uuid, jsonb),
  public.server_post_capital_payment(uuid, jsonb), public.server_post_payment_adjustment(uuid, jsonb),
  public.server_edit_transaction(uuid, jsonb), public.server_void_transaction(uuid, uuid, text),
  public.server_record_audit_event(uuid, uuid, text, text, text, jsonb),
  public.server_create_customer(uuid, uuid, text, text, text),
  public.server_update_customer(uuid, uuid, uuid, boolean, text, text, text),
  public.server_update_organization_settings(uuid, uuid, text, text, jsonb)
  to service_role;

revoke all on function private.assume_server_actor(uuid) from public, anon, authenticated;
grant execute on function public.update_my_profile(text, text) to authenticated;
